name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Prepare tests
      run: |
        sudo apt-get install -y netcat
        sudo sysctl -w vm.max_map_count=262144

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Run Docker containers
      run: docker-compose up -d

    - name: Check Docker containers
      run: docker ps -a

    - name: Get dependencies
      run: |
        go get -u github.com/google/go-cmp/cmp
        go get -u github.com/fortytw2/leaktest
        go get . ./aws/... ./config/... ./trace/... ./uritemplates/...

    - name: Wait for Elasticsearch
      run: |
        while ! nc -z localhost 9200; do sleep 1; done
        while ! nc -z localhost 9210; do sleep 1; done

    - name: Run the tests
      run: |
        go test -race -deprecations -strict-decoder -v . ./aws/... ./config/... ./trace/... ./uritemplates/...
