name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Prepare tests
      run: |
        sudo apt-get install -y netcat-openbsd
        sudo sysctl -w vm.max_map_count=262144

    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Setup Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      with:
        go-version-file: 'go.mod'

    - name: Run Docker containers
      run: docker compose up -d

    - name: Check Docker containers
      run: docker ps -a

    - name: Get dependencies
      run: |
        go get -u github.com/google/go-cmp/cmp
        go get -u github.com/fortytw2/leaktest
        go get . ./config/... ./uritemplates/...

    - name: Wait for Elasticsearch
      run: |
        while ! nc -z localhost 9200; do sleep 1; done
        while ! nc -z localhost 9210; do sleep 1; done

    - name: Run the tests
      run: |
        go test -race -deprecations -strict-decoder -v . ./config/... ./uritemplates/...
